### ISSUE TITLE
Export roller geometry in a way that is suitable for plotting

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-export#6]
Export roller geometry in a way that is suitable for plotting.

E.g. as a closed polygon with all rollers rotated in correct positon.

![image](https://github.com/pyroll-project/pyroll-export/assets/144011375/80c86724-121c-442d-8359-f6248df01c4e)

**Comment by ChRen95** [comment]
Okay, so by going through all the other issues I will combine the tasks. 
- Make the property `contour_lines` of class `RollPass` availabe in the export
- Make sure that the property is already in it's correct technological representation -> already handled by `pyroll-core` if the hooks `orientation` are set.

**Comment by axtimhaus** [comment]
Should already be solved with https://github.com/pyroll-project/pyroll-core/pull/243 (except the "technological" orientation)

**Comment by ChRen95** [comment]
As agreed yesterday, we will add a hook for this in the core.
