### ISSUE TITLE
Remove dtype_convert() call in function to_pandas

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-export#9]
Without the dtype_convert() call in function to_pandas eval-function is more reliable in exported dataframe.

Lesson learned during template-development

**Comment by ChRen95** [comment]
What is the suspected improvement from this change? I mean if we remove the function the memory size allocated by the dataframe increases witch makes handling of the dataframe harder on systems with lower RAM and CPU power. 
On the other hand removing the function call would give a "raw" dataframe leaving every further manipulation to the end user witch I tend to like more.

**Comment by GRPlan** [comment]
In short pandas seems to have issues with extension dtypes(). Especially the convenient eval() and query() methods.
E.g. https://github.com/open2c/pairtools/issues/143
Therefore I would suggest to stick to the basic dtypes.

**Comment by ChRen95** [comment]
Okay, after reading into this I agree.
